### ISSUE TITLE
Fix Time Output

### ISSUE THREAD

**Issue by cma5** [ID-Start-Winter22/chat-team-11#11]
As a Chatbot User I want to receive nicely formatted departure and arrival time.

The current time output of the bot is:

 Abfahrtszeit: 2022-11-23T09:39:00.000Z
 Ankunftszeit: 2022-11-23T15:45:00.000Z

A better time output would be:
"Ankunftszeit: Heute um 9:39 Uhr."

**Comment by lynnstarke** [comment]
Fixed it!

**Comment by theopfr** [comment]
Issues in der Wiki: https://github.com/ID-Start-Winter22/chat-team-11/wiki/%F0%9F%8F%83%E2%80%8D%E2%99%82%EF%B8%8F-Ideation-und-Sprint-1#-issues
