### ISSUE TITLE
Add bot answer if he doesn't understand the user message

### ISSUE THREAD

**Issue by theopfr** [ID-Start-Winter22/chat-team-11#15]
As a chatbot user I want the chatbot to tell me if he didn't understand my message.

Acceptance criteria:
For the following answers here are examples given:
**Chatbot User:** "Ich mag Züge."
**Chatbot Answer:** "Tut mir leid! Das hab ich leider nicht verstanden."

### **EXCEPTION**
**Chatbot User:** "aisefpdiufahvdp" (gibberish)
The chatbot cannot understand gibberish in every situation and possibly recognizes it as another given intent. Therefore, it is possible for it to answer "Tschüss bis zum nächsten Mal!" or "Mir geht es gut! Danke!", etc.

**Comment by lynnstarke** [comment]
Done! @theopfr @cma5

**Comment by theopfr** [comment]
Issues in der Wiki: https://github.com/ID-Start-Winter22/chat-team-11/wiki/%F0%9F%8F%83%E2%80%8D%E2%99%82%EF%B8%8F-Ideation-und-Sprint-1#-issues
