### ISSUE TITLE
Add intents and answers for small talk

### ISSUE THREAD

**Issue by theopfr** [ID-Start-Winter22/chat-team-11#16]
As a chatbot user I want the bot to be able answer a few small talk questions. 

### **Examples:**
**Chatbot User:** "Danke."
**Chatbot Answer:** "Bitte."

**Chatbot User:** "Tschüss."
**Chatbot Answer:** "Bist zum nächsten Mal!"

**Chatbot User:** "Du bist toll!"
**Chatbot Answer:** "Danke, ich weiß!"

**Comment by lynnstarke** [comment]
Done!

**Comment by theopfr** [comment]
Issues in der Wiki: https://github.com/ID-Start-Winter22/chat-team-11/wiki/%F0%9F%8F%83%E2%80%8D%E2%99%82%EF%B8%8F-Ideation-und-Sprint-1#-issues
