### ISSUE TITLE
Associate our AWS EC2 Instance with an elastic IP

### ISSUE THREAD

**Issue by cma5** [ID-Start-Winter22/chat-team-11#33]
As a user, I want to access the chatbot always from the same address. 

If we deactivate our server, the IP changes so the user can't access the server without the new IP.
Expected results: http://34.251.35.212/ always available, even if the server is down.

**Comment by theopfr** [comment]
Issues in der Wiki: https://github.com/ID-Start-Winter22/chat-team-11/wiki/%F0%9F%8F%83%E2%80%8D%E2%99%82%EF%B8%8F-Ideation-und-Sprint-1#-issues
