### ISSUE TITLE
Get info about Train Stations

### ISSUE THREAD

**Issue by cma5** [ID-Start-Winter22/chat-team-11#53]
As a user I want to know which train stations the train stops:

Acceptence criteria:
When a user asks for example: "Welche Stationen gibt es?" he want's to recieve an answer like: 
Folgende Stationen gibt es auf der Strecke:
Basel SBB, Basel Bad Bf, Freiburg(Breisgau) Hbf, Offenburg, Karlsruhe Hbf, Mannheim Hbf, Frankfurt(M) Flughafen Fernbf, Siegburg/Bonn, Köln Hbf, 
Düsseldorf Hbf, Duisburg Hbf, Oberhausen Hbf, Arnhem Centraal, Utrecht Centraal, Amsterdam Centraal

**Comment by theopfr** [comment]
haben wir doch schon lange fertig oder? @cma5

**Comment by cma5** [comment]
Stimmt, das ham wir fertig! Ich schließ es gleich mal.

> haben wir doch schon lange fertig oder? @cma5
