### ISSUE TITLE
Add intent and bot answer(s) for user confirmation

### ISSUE THREAD

**Issue by theopfr** [ID-Start-Winter22/chat-team-11#59]
As a user I want the chatbot to understand when I am confirming something.

## Acceptence criterea:
The bot should be able to answer to messages like "okay", "verstanded", "ja", etc.

### Previous behaviour:
> user: Wann fährt nochmal der Zug ab?
> bot: Der Zug fährt Heute um 12:35 ab.
> user: okay
> bot: Tut mir Leid, das habe ich nicht verstanden!

### Expected behaviour:
> user: Wann fährt nochmal der Zug ab?
> bot: Der Zug fährt Heute um 12:35 ab.
> user: okay
> bot: Super / Gut, dass ich helfen konnte / 👍🏻 / etc.

**Comment by theopfr** [comment]
@cma5 @lynnstarke wer will das machen? könnt euch selber assignen, sonst kann ichs auch machen :)

**Comment by cma5** [comment]
> @cma5 @lynnstarke wer will das machen? könnt euch selber assignen, sonst kann ichs auch machen :)

Mach ich :)

**Comment by theopfr** [comment]
Lasst uns dieses Issue mit dem hier: https://github.com/ID-Start-Winter22/chat-team-11/issues/60 mergen. Ist das okay? @cma5
